from .player import Player
from .simple_player import SimplePlayer
from .decorate_logger import add_logging
from .learning_player import LearningPlayer
from .monte_carlo import MonteCarlo
from .monte_carlo import EpsilonMonteCarlo
from .optimal import Optimal
from .sarsa import Sarsa
from .q_learning import QLearning